import Foundation
import Shared
import AIProcessing

/// Generates daily summary notes that aggregate the day's ScreenMind captures.
public struct DailySummaryWriter: Sendable {
    private let vaultManager: VaultManager

    public init(vaultManager: VaultManager = VaultManager()) {
        self.vaultManager = vaultManager
    }

    /// Write or update the daily summary note.
    public func writeSummary(notes: [NoteModel], for date: Date = .now) throws {
        guard !notes.isEmpty else { return }

        let folder = try vaultManager.ensureDailyFolder(for: date)
        let fileURL = folder.appendingPathComponent("_daily-summary.md")

        let categories = Dictionary(grouping: notes, by: { $0.category })
        let appCounts = Dictionary(grouping: notes, by: { $0.appName })
            .mapValues { $0.count }
            .sorted { $0.value > $1.value }

        var md = """
        ---
        title: "Daily Summary — \(date.dateFolderName)"
        date: \(date.iso8601String)
        type: daily-summary
        source: \(AppConstants.Obsidian.sourceTag)
        note_count: \(notes.count)
        ---

        # Daily Summary — \(date.dateFolderName)

        **\(notes.count) notes** captured today.\n\n
        """

        // App breakdown
        md += "## Apps Used\n\n"
        for (app, count) in appCounts {
            md += "- **\(app)**: \(count) notes\n"
        }
        md += "\n"

        // Category breakdown
        md += "## By Category\n\n"
        for (category, catNotes) in categories.sorted(by: { $0.value.count > $1.value.count }) {
            md += "### \(category.capitalized) (\(catNotes.count))\n\n"
            for note in catNotes.prefix(5) {
                md += "- \(note.title)\n"
            }
            if catNotes.count > 5 {
                md += "- *...and \(catNotes.count - 5) more*\n"
            }
            md += "\n"
        }

        md += "---\n*Generated by ScreenMind*\n"

        try md.write(to: fileURL, atomically: true, encoding: .utf8)
        SMLogger.storage.info("Daily summary updated: \(notes.count) notes")
    }
}
