import Foundation
import Shared
import AIProcessing

/// Writes AI-generated notes as Obsidian-compatible markdown files.
public struct ObsidianNoteWriter: Sendable {
    private let vaultManager: VaultManager

    public init(vaultManager: VaultManager = VaultManager()) {
        self.vaultManager = vaultManager
    }

    /// Write a note to the Obsidian vault. Returns the file URL on success.
    public func write(note: GeneratedNote, appName: String, windowTitle: String?, timestamp: Date) throws -> URL {
        guard vaultManager.isVaultAccessible else {
            SMLogger.storage.warning("Obsidian vault not accessible — skipping export")
            throw ObsidianError.vaultNotAccessible
        }

        let folder = try vaultManager.ensureDailyFolder(for: timestamp)
        let filename = safeFilename(from: note.title, timestamp: timestamp)
        let fileURL = folder.appendingPathComponent(filename)

        let frontmatter = FrontmatterBuilder.build(
            title: note.title,
            category: note.category.rawValue,
            tags: note.tags,
            appName: appName,
            windowTitle: windowTitle,
            confidence: note.confidence,
            createdAt: timestamp
        )

        var markdown = frontmatter + "\n\n"
        markdown += "## \(note.title)\n\n"
        markdown += "\(note.summary)\n\n"

        if !note.details.isEmpty {
            markdown += "### Details\n\n"
            markdown += "\(note.details)\n\n"
        }

        if !note.obsidianLinks.isEmpty {
            markdown += "### Related\n\n"
            for link in note.obsidianLinks {
                markdown += "- \(link)\n"
            }
            markdown += "\n"
        }

        markdown += "---\n"
        markdown += "*Generated by ScreenMind from \(appName)*\n"

        try markdown.write(to: fileURL, atomically: true, encoding: .utf8)
        SMLogger.storage.info("Obsidian note written: \(fileURL.lastPathComponent)")
        return fileURL
    }

    /// Generate a safe filename from the note title.
    private func safeFilename(from title: String, timestamp: Date) -> String {
        let timeString = Self.timeFormatter.string(from: timestamp)
        let safe = title.safeFilename
        let truncated = String(safe.prefix(60))
        return "\(timeString)-\(truncated).md"
    }

    private static let timeFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "HHmm"
        return f
    }()
}

/// Obsidian export errors.
public enum ObsidianError: Error, LocalizedError {
    case vaultNotAccessible
    case writeFailed(String)

    public var errorDescription: String? {
        switch self {
        case .vaultNotAccessible: return "Obsidian vault is not accessible"
        case .writeFailed(let detail): return "Failed to write note: \(detail)"
        }
    }
}
